language: rust
rust:
  - stable

matrix:
  fast_finish: true

#before_install:
#  - cd ..
#  - wget https://www.dropbox.com/s/axupvg88yzdmsu5/rustdev.tar-gz?dl=1 -O rustdownload.tar.gz
#  - tar -xzf rustdownload.tar.gz
#  - ls rustdev/build/x86_64-unknown-linux-gnu/stage2/bin/rustc
#  - RDEV=$(pwd)/rustdev/build/x86_64-unknown-linux-gnu/stage2/bin/rustc
#  - pwd

#before_script:
#  - echo "Building cargo from "$TRAVIS_COMMIT " "$TRAVIS_COMMIT_MESSAGE
#  - $RDEV --version

script:
#  - cd mononoke
  - echo "Testing with nightly version"
  - cargo build --all
# - RUSTC=$RDEV cargo build --all
#  - echo "Testing with version "$($RDEV --version)
