[workspace]
members = [
    "asyncmemo",
    # depends on failure_ext
    # "blobrepo",
    # "bookmarks",
    # "bundle2-resolver",
    "bytes-ext",
    # depends on failure_ext
    # "changesets",
    # "common/pylz4",
    "futures-ext",
    "storage/types",
]
